version: '3.1'

volumes:
  postgres_data:
    driver: local

services:
  gateway:
    image: gateway:latest
    ports:
      - 8087:8087
    environment:
      - EUREKA_URL=http://eureka:8761/eureka

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres

  eureka:
    image: eureka-server:latest
    ports:
      - 8761:8761
    environment:
      - EUREKA_URL=http://eureka:8761/eureka