spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${SERVICE_KAFKA_HOST:localhost:9092}
          autoCreateTopics: true
      bindings:
        paymentChannel:
          binder: kafka
          destination: ${PAYMENT_EVENTS_TOPIC:paymentEventsTopic}
          contentType: application/json
        clientChannel:
          binder: kafka
          destination: ${CLIENT_EVENTS_TOPIC:clientEventsTopic}
          contentType: application/json
        orderChannel:
          binder: kafka
          destination: ${ORDER_EVENTS_TOPIC:orderEventsTopic}
          contentType: application/json
    discovery:
      enabled: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/order_db?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Moscow}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Password123}
  jpa:
    hibernate.ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${IDENTITY_SERVICE_JWK_URL:http://localhost:8082/auth/realms/test/protocol/openid-connect/certs}
          issuer-uri: ${IDENTITY_SERVICE_ISSUER_URL:http://localhost:8082/auth/realms/test}
events:
  delay: 4000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
server:
  port: 8085